# Curso de Manipulación de Pandas y Numpy

Manejo y transformación de datos con dos librerias muy importantes para data science

#Creación de arrays con numpy

In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

El metodo zeros nos sirve para definir estructuras previas.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Funcion eye nos da una diagonal para algebra lineal

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Nos da un valor aleatorio entre cero y uno cada vez que se ejecute el metodo random.rand

In [ ]:
np.random.rand()

0.6361857491997536

In [ ]:
np.random.rand(4,4)

array([[0.5863698 , 0.57799702, 0.81080588, 0.07784659],
       [0.98844063, 0.63740534, 0.84116078, 0.75157239],
       [0.65592963, 0.41685911, 0.89660701, 0.92909642],
       [0.27793167, 0.4175226 , 0.9974648 , 0.33852393]])

In [ ]:
np.random.randint(1,10,(10,10))

array([[9, 5, 9, 3, 9, 7, 9, 9, 2, 2],
       [5, 2, 6, 4, 3, 2, 7, 7, 8, 5],
       [7, 6, 6, 3, 3, 7, 3, 7, 8, 9],
       [8, 3, 1, 3, 5, 8, 5, 9, 5, 3],
       [2, 8, 8, 7, 3, 5, 3, 9, 3, 2],
       [5, 9, 7, 3, 5, 3, 9, 7, 4, 7],
       [2, 6, 8, 1, 8, 7, 4, 8, 2, 6],
       [6, 4, 6, 6, 6, 5, 7, 4, 7, 4],
       [6, 8, 7, 5, 3, 7, 6, 1, 7, 3],
       [1, 3, 5, 1, 8, 2, 9, 2, 3, 7]])

In [ ]:
False or True

True

#Shape and Reshape

In [ ]:
arr=np.random.randint(1,10,(3,2))
print(arr)

[[3 7]
 [5 5]
 [5 5]]


In [ ]:
arr.shape

(3, 2)

In [ ]:
arr.reshape(1,6)

array([[3, 7, 5, 5, 5, 5]])

#Funciones principales NP


In [ ]:
arr = np.random.randint(1,20,10)
matrix = arr.reshape(2,5)
matrix

array([[11,  3,  6,  1,  9],
       [ 9,  9,  1, 10,  2]])

In [ ]:
matrix.max(0)

array([11,  9,  6, 10,  9])

In [ ]:
matrix.argmax()

0

In [ ]:
arr.ptp()


15

In [ ]:
np.percentile(arr,50)

10.5

In [ ]:
arr.sort()
arr

array([ 1,  3,  5,  7,  7, 14, 15, 15, 15, 16])

In [ ]:
np.std(arr)

5.473572873361603

In [ ]:
np.var(arr)

29.959999999999997

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

#Copy

Es bueno siempre cuando se quiera modificar un array, realizar una copia para que no te modifique el arreglo padre


In [ ]:
arr = np.arange(0,11)

In [ ]:
troso_de_arr = arr [0:6]
troso_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
troso_de_arr [:] = 0
troso_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr_copy = arr.copy()

# Condiciones con arreglos

In [ ]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
ind_con = arr > 5

In [ ]:
arr[ind_con]

array([ 6,  7,  8,  9, 10], dtype=int8)

# Operaciones

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista * 2

[1, 2, 1, 2]

Lo anterior python lo entiende como si quisieramos duplicar los datos, si deseamos realizar operaciones matematicas, utilizaremos numpy de esta forma:

In [ ]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Con numpy si se reconoce que se requiere realizar la operación con cada uno de los datos del arreglo

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matrix = arr.reshape (2,5)
matrix2 = matrix.copy()

In [ ]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

Operación con la transpuesta

In [ ]:
matrix2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
np.matmul(matrix, matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

# Quiz de arreglos

In [ ]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
np.array([1,2,3]).ndim

1

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#Pandas

1. Pandas series - areglos
2. Pandas Dataframe - Matricial

In [ ]:
import pandas as pd

In [ ]:
pd.Series(['navas', 'Mbampe', 'Messi'],
          index=[1,7,10])

1      navas
7     Mbampe
10     Messi
dtype: object

In [ ]:
dict = {'Jugador' : ['navas', 'Mbampe', 'Messi'],
        'Altura' : [180.0, 183.0, 175.0],
        'Goles' : [2, 200, 500]
}

In [ ]:
pd.DataFrame(dict, index=[1,7,10])

Jugador  Altura  Goles
1    navas   180.0      2
7   Mbampe   183.0    200
10   Messi   175.0    500

#Leer archivos con Pandas

In [ ]:
dt_books = pd.read_csv('/content/bestsellers with categories.csv')

#LOC y ILOC

In [ ]:
dt_books.loc[0:4, ['Name', 'Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [ ]:
dt_books.iloc[:, 0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

#Valores Nulos

In [ ]:
dict = {'Col1':[1,2,3,np.nan],
 'Col2':[4,np.nan,6,7],
 'Col3':['a','b','c',np.nan]
}

dataframe = pd.DataFrame(dict)
dataframe

Col1  Col2 Col3
0   1.0   4.0    a
1   2.0   NaN    b
2   3.0   6.0    c
3   NaN   7.0  NaN

In [ ]:
dataframe.fillna('missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  missing        b
2      3.0      6.0        c
3  missing      7.0  missing

In [ ]:
dataframe.interpolate()

Col1  Col2 Col3
0   1.0   4.0    a
1   2.0   5.0    b
2   3.0   6.0    c
3   3.0   7.0  NaN

In [ ]:
dataframe.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

#Filtrado por condiciones

In [ ]:
df_books = pd.read_csv('/content/bestsellers with categories.csv')

In [ ]:
mayorA2016 = df_books['Year'] < 2016

In [ ]:
gene_fiction = df_books['Genre'] == 'Fiction'

In [ ]:
df_books[mayorA2016 & gene_fiction]

Name               Author  \
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
20                         All the Light We Cannot See        Anthony Doerr   
21                         All the Light We Cannot See        Anthony Doerr   
..                                                 ...                  ...   
535                          Where the Wild Things Are       Maurice Sendak   
538  Winter of the World: Book Two of the Century T...          Ken Follett   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   

     User Rating  Reviews  Price  Year    Genre  
1            4.6     2052     22  2011  Fiction  
5            4.4    12643     11  2011  Fiction  
6            4.7    19735     30  2014  Fiction  
20           4.6    36348     14  2014  Fiction  
21           4.6    36348     14  2015  Fiction  
..           ...      ...    ...   ...      ...  
535          4.8     9967     13  2009  Fiction  
538          4.5    10760     15  2012  Fiction  
540          4.8    21625      9  2013  Fiction  
541          4.8    21625      9  2014  Fiction  
542          4.8    21625      9  2015  Fiction  

[156 rows x 7 columns]

#Funciones principales de Pandas

In [ ]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [ ]:
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [ ]:
df_books.tail(2)

Name       Author  \
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

In [ ]:
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [ ]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [ ]:
df_books1 = pd.concat([df_books, df_books.iloc[0].to_frame().T], ignore_index=True)

In [ ]:
df_books1.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author User Rating Reviews Price  Year        Genre  
0                    JJ Smith         4.7   17350     8  2016  Non Fiction  
1                Stephen King         4.6    2052    22  2011      Fiction  
2          Jordan B. Peterson         4.7   18979    15  2018  Non Fiction  
3               George Orwell         4.7   21424     6  2017      Fiction  
4    National Geographic Kids         4.8    7665    12  2019  Non Fiction  
..                        ...         ...     ...   ...   ...          ...  
545               Jeff Kinney         4.9    9413     8  2019      Fiction  
546               Jen Sincero         4.7   14331     8  2016  Non Fiction  
547               Jen Sincero         4.7   14331     8  2017  Non Fiction  
548               Jen Sincero         4.7   14331     8  2018  Non Fiction  
549               Jen Sincero         4.7   14331     8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.sort_values('Year', ascending=True)

Name            Author  \
513               Twilight (The Twilight Saga, Book 1)   Stephenie Meyer   
418  The Last Olympian (Percy Jackson and the Olymp...      Rick Riordan   
177                                      I, Alex Cross   James Patterson   
417                                   The Last Lecture      Randy Pausch   
331  The 7 Habits of Highly Effective People: Power...  Stephen R. Covey   
..                                                 ...               ...   
150                                               Guts  Raina Telgemeier   
466  The Subtle Art of Not Giving a F*ck: A Counter...       Mark Manson   
462                                 The Silent Patient  Alex Michaelides   
130  Girl, Wash Your Face: Stop Believing the Lies ...     Rachel Hollis   
155  Harry Potter and the Goblet of Fire: The Illus...     J. K. Rowling   

     User Rating  Reviews  Price  Year        Genre  
513          4.7    11676      9  2009      Fiction  
418          4.8     4628      7  2009      Fiction  
177          4.6     1320      7  2009      Fiction  
417          4.7     4028      9  2009  Non Fiction  
331          4.6     9325     24  2009  Non Fiction  
..           ...      ...    ...   ...          ...  
150          4.8     5476      7  2019  Non Fiction  
466          4.6    26490     15  2019  Non Fiction  
462          4.5    27536     14  2019      Fiction  
130          4.6    22288     12  2019  Non Fiction  
155          4.9     7758     18  2019      Fiction  

[552 rows x 7 columns]

#Groupby

In [ ]:
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [ ]:
df_books.groupby('Author').agg(['min', 'max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

#Combinando datasets

Merge - Join
1. left join
2. right join
3. inner join
4. outer join

Concat Axis N

In [ ]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2','A3'],
	'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']})

In [ ]:
df2 = pd.DataFrame({'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']})

In [ ]:
pd.concat([df1,df2], axis=1, ignore_index=True)

0   1   2   3   4   5   6   7
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

#Merge

In [ ]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [ ]:
izq.merge(der)

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [ ]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [ ]:
izq.merge(der, left_on='key', right_on='key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2
3  k3  A3  B3    k3  C3  D3

In [ ]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2',np.nan],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [ ]:
izq.merge(der, left_on='key', right_on='key_2', how='left')

key   A   B key_2    C    D
0  k0  A0  B0    k0   C0   D0
1  k1  A1  B1    k1   C1   D1
2  k2  A2  B2    k2   C2   D2
3  k3  A3  B3   NaN  NaN  NaN

#Join

In [ ]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']},
  index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']},
  index=['k0','k2','k3'])

In [ ]:
izq.join(der, how='outer')

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

#Pivot y Melt

In [ ]:
df_books.head(5)

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [ ]:
df_books.pivot_table(index='Author',columns='Genre',values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [ ]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='count')

Year         2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019
Genre                                                                        
Fiction        24    20    21    21    24    29    17    19    24    21    20
Non Fiction    26    30    29    29    26    21    33    33    26    29    30

In [ ]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [ ]:
df_books[['Name','Genre']].head(5).melt()

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [ ]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction
550  2016    Genre  Non Fiction
551  2016    Genre  Non Fiction

[552 rows x 3 columns]

#Apply

In [ ]:
def two_times(values):
  return values *2

In [ ]:
df_books['User Rating'].apply(lambda x: x*3)

0      14.1
1      13.8
2      14.1
3      14.1
4      14.4
       ... 
547    14.1
548    14.1
549    14.1
0      14.1
0      14.1
Name: User Rating, Length: 552, dtype: float64